### ISSUE TITLE
'Parent_pnr_frame' missing in 'fho_oscc-pnr_train.json'

### ISSUE THREAD

**Issue by HimangiM** [EGO4D/hands-and-objects#8]
Hi,

@Sid2697, Thank you for sharing the amazing work! I was running into a small issue while running the code. I was trying to run the i3d-resnet50/train.py and there seems to be an error at this line (https://github.com/EGO4D/hands-and-objects/blob/main/state-change-localization-classification/i3d-resnet50/datasets/StateChangeDetectionAndKeyframeLocalisation.py#L64). I noticed that some of the entries in 'fho_oscc-pnr_train.json' do not have the key 'parent_pnr_frame'. Could you please let me know how to resolve this?

Thanks!

**Comment by Sid2697** [comment]
Hello @HimangiM, Thank you for reaching out and bringing this issue to our notice!

I looked into 'fho_oscc_pnr_train.json' and it turns out that for the negative clips (without a state change), instead of having `parent_pnr_frame` as the key, `pnr_frame` is the key.

To fix this, you can simply add a check on the same line and take information from `pnr_frame` when `parent_pnr_frame` is not present.

Feel free to create a pull request to fix this issue! We will be happy to review and merge it.

Thanks!
